
# The following are the loadable configurations for the SSA Daemon.
# If a configuration is not set in this YAML file, the default will be use
# (as listed to the right/bottom of each setting)


# TLS Protocols include 0, 1, 2, 3 (corresponding to TLSv1.0, TLSv1.1...). Note 
# that SSLv2 and SSLv3 cannot be enabled (due to considerable security flaws).
# Note that protocols lower than TLS-1.2 are considered deprecated and insecure 
# by most browsers.
min-tls-version: 2 # Default: 2 (TLSv1.2)
max-tls-version: 3 # Default: 3 (TLSv1.3)

# The following is commented out since the SSA Daemon automatically uses the 
# OS CA path based on what Linux distro is being run.
# CA-path can be a file or directory of CA files. All files must be in PEM 
# format. Use "c_rehash ." in directory before use. 
#  CA-path: /etc/ssl/certs
#  CA-path: test_files/certs/rootCA.pem # use this for our test server

session-tickets: disabled  # Default: disabled

# Default ciphers in this list (and added by the SSA Daemon in the event of no 
# configuration file found) all maintain Forward Secrecy (the second 'E' in 
# ECDHE is for Ephemeral). NULL, RC4, MD4 and MD5 ciphers SHOULD NOT be allowed 
# in this list, and SHA128 is also considered insecure. Make sure to research 
# your cipher before adding it to this list.
cipher-list: 
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256

  # Defaults: - ECDHE-ECDSA-AES256-GCM-SHA384
  #           - ECDHE-RSA-AES256-GCM-SHA384
  #           - ECDHE-ECDSA-CHACHA20-POLY1305
  #           - ECDHE-RSA-CHACHA20-POLY1305
  #           - ECDHE-ECDSA-AES128-GCM-SHA256
  #           - ECDHE-RSA-AES128-GCM-SHA256

# These are the only ciphersuites accepted by TLS 1.3; they're all very safe.
# Note that while CCM ciphers are technically safe, they posess properties that 
# may make them unsafe for future use.
ciphersuites:
  - TLS_AES_256_GCM_SHA384
  - TLS_AES_128_GCM_SHA256
  - TLS_CHACHA20_POLY1305_SHA256

# Defaults: - TLS_AES_256_GCM_SHA384
#           - TLS_AES_128_GCM_SHA256
#           - TLS_CHACHA20_POLY1305_SHA256

# Sessions older than the session timeout are not reused.  Value is in seconds.
session-timeout: 300 # Default: 300 seconds

# Set the maximum number of certificates that can be traversed before 
# certification fails.
cert-verification-depth: 10
# Default: 10. This allows for the peer certificate, at most 10 intermediate CA 
# certificates and a final trust anchor certificate.

# Enable certificate transparency verification. Servers that do not provide a 
# valid SCT will not be connected with. Provides greater security by guarding 
# against several types of CA compromise threats.
# See http://www.certificate-transparency.org/what-is-ct for more information.
cert-transparency-checks: disabled
# Default: enabled

# Certificate Revocation checks are important in determining the authenticity 
# of a webiste's certificate.
revocation-checks: disabled
# Default: enabled

session-resumption: enabled