# This configuration is meant to have its settings applied in such a way that 
# testing suites can configure any of the options to be more strict, or leave 
# them relaxed.

min-tls-version: 1.0
max-tls-version: 1.3

CA-path: test_files/certs/rootCA.pem

cipher-list: 
  - ECDHE-ECDSA-AES256-GCM-SHA384
  - ECDHE-RSA-AES256-GCM-SHA384
  - ECDHE-ECDSA-CHACHA20-POLY1305
  - ECDHE-RSA-CHACHA20-POLY1305
  - ECDHE-ECDSA-AES128-GCM-SHA256
  - ECDHE-RSA-AES128-GCM-SHA256

ciphersuites:
  - TLS_AES_256_GCM_SHA384
  - TLS_AES_128_GCM_SHA256
  - TLS_CHACHA20_POLY1305_SHA256
  - TLS_AES_128_CCM_SHA256
  - TLS_AES_128_CCM_8_SHA256

cert-verification-depth: 100

verify-cert-transparency: off
revocation-checks: off
revocation-stapled: enabled
revocation-ocsp: enabled
revocation-crl: enabled
revocation-cached: enabled

session-resumption: enabled
session-tickets: on
session-timeout: 86400