client:
  min-tls-version: 1.2       # TLS 1.1 and lower are considered deprecated by most browsers
  max-tls-version: 1.3       # TLS 1.3 is the highest current TLS version
  tls-compression: disabled  # The CRIME attack targets TLS Compression. It should be disabled.
  session-tickets: disabled  # Session Tickets are also vulnerable to an attack.

  cipher-list: 
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
  
  ciphersuites:
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_AES_128_CCM_SHA256
    - TLS_AES_128_CCM_8_SHA256


server:
  min-tls-version: 1.2       # TLS 1.1 and lower are considered deprecated by most browsers
  max-tls-version: 1.3       # TLS 1.3 is the highest current TLS version
  tls-compression: disabled  # The CRIME attack targets TLS Compression. It should be disabled.
  session-tickets: disabled  # Session Tickets are also vulnerable to an attack.

  CA-path: test_files/certs/rootCA.pem

  cipher-list: 
    - ECDHE-ECDSA-AES256-GCM-SHA384
    - ECDHE-RSA-AES256-GCM-SHA384
    - ECDHE-ECDSA-CHACHA20-POLY1305
    - ECDHE-RSA-CHACHA20-POLY1305
    - ECDHE-ECDSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
  
  ciphersuites:
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_AES_128_CCM_SHA256
    - TLS_AES_128_CCM_8_SHA256