#include <gtest/gtest.h>

#include <future>
#include <stdlib.h>
#include <string>

#include "timeouts.h"

extern "C" { // To indicate that the code is C code when linking--important

#include "helper_functions.h"

const char* ERR_SOURCE_CONNECT = "connect()";
const char* ERR_SOURCE_HOSTNAME = "TLS_HOSTNAME getsockopt()";
#define HTTPS_PORT "443"

}

#define TEST_CONNECT_FAIL(testname, hostname_str)                   \
    TEST(BadSSLTests, testname) {                                   \
                                                                    \
        TEST_TIMEOUT_BEGIN                                          \
                                                                    \
        const int NO_ERRNO = 0;                                     \
        struct sockaddr* addr;                                      \
        socklen_t addrlen;                                          \
        std::string hostname = hostname_str;                        \
        std::string port = HTTPS_PORT;                              \
        int dns_failed;                                             \
        int fd;                                                     \
                                                                    \
                                                                    \
        dns_failed = resolve_dns(hostname.c_str(),                  \
                    port.c_str(), &addr, &addrlen);                 \
        ASSERT_EQ(dns_failed, 0);                                   \
                                                                    \
        fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TLS);             \
        int socket_errno = errno;                                   \
        if (fd == -1)                                               \
            perror("socket creation failed");                       \
                                                                    \
        EXPECT_EQ(socket_errno, 0);                                 \
        ASSERT_GE(fd, 0);                                           \
                                                                    \
        int hostname_ret = setsockopt(fd, IPPROTO_TLS,              \
                TLS_HOSTNAME, hostname.c_str(), hostname.size()+1); \
        int hostname_errno = errno;                                 \
        if (hostname_ret != 0)                                      \
            print_socket_error(fd, ERR_SOURCE_HOSTNAME);            \
                                                                    \
        EXPECT_EQ(hostname_errno, 0);                               \
        ASSERT_EQ(hostname_ret, 0);                                 \
                                                                    \
        int connect_ret = connect(fd, addr, addrlen);               \
        int connect_errno = errno;                                  \
                                                                    \
        if (connect_ret != 0)                                       \
            print_socket_error(fd, ERR_SOURCE_CONNECT);             \
                                                                    \
        EXPECT_EQ(connect_errno, NO_ERRNO);                         \
        ASSERT_EQ(connect_ret, 0);                                  \
                                                                    \
        free(addr);                                                 \
        close(fd);                                                  \
                                                                    \
        TEST_TIMEOUT_FAIL_END(TIMEOUT_LONG)                         \
                                                                    \
    }




class Top500WebsitesTest : public testing::Test {
public:
    char *resp;
    int resp_len;
    int result;

    virtual void SetUp() {
        resp = NULL;
        resp_len = 0;
        result = 0;
    }

    virtual void TearDown() { }
};

/* top 500 websites per `moz.com` */

TEST_CONNECT_FAIL(www_google_com, "www.google.com")
TEST_CONNECT_FAIL(apple_com, "apple.com")
TEST_CONNECT_FAIL(youtube_com, "youtube.com")
TEST_CONNECT_FAIL(play_google_com, "play.google.com")
TEST_CONNECT_FAIL(docs_google_com, "docs.google.com")
TEST_CONNECT_FAIL(microsoft_com, "microsoft.com")
TEST_CONNECT_FAIL(support_google_com, "support.google.com")
TEST_CONNECT_FAIL(www_blogger_com, "www.blogger.com")
TEST_CONNECT_FAIL(linkedin_com, "linkedin.com")
TEST_CONNECT_FAIL(plus_google_com, "plus.google.com")
TEST_CONNECT_FAIL(maps_google_com, "maps.google.com")
TEST_CONNECT_FAIL(adobe_com, "adobe.com")
TEST_CONNECT_FAIL(cloudflare_com, "cloudflare.com")
TEST_CONNECT_FAIL(wordpress_org, "wordpress.org")
TEST_CONNECT_FAIL(en_wikipedia_org, "en.wikipedia.org")
TEST_CONNECT_FAIL(accounts_google_com, "accounts.google.com")
TEST_CONNECT_FAIL(europa_eu, "europa.eu")
TEST_CONNECT_FAIL(sites_google_com, "sites.google.com")
TEST_CONNECT_FAIL(googleusercontent_com, "googleusercontent.com")
TEST_CONNECT_FAIL(vimeo_com, "vimeo.com")
TEST_CONNECT_FAIL(drive_google_com, "drive.google.com")
TEST_CONNECT_FAIL(mozilla_org, "mozilla.org")
TEST_CONNECT_FAIL(youtu_be, "youtu.be")
TEST_CONNECT_FAIL(line_me, "line.me")
TEST_CONNECT_FAIL(istockphoto_com, "istockphoto.com")
TEST_CONNECT_FAIL(es_wikipedia_org, "es.wikipedia.org")
TEST_CONNECT_FAIL(bp_blogspot_com, "bp.blogspot.com")
TEST_CONNECT_FAIL(facebook_com, "facebook.com")
TEST_CONNECT_FAIL(bbc_co_uk, "bbc.co.uk")
TEST_CONNECT_FAIL(creativecommons_org, "creativecommons.org")
TEST_CONNECT_FAIL(vk_com, "vk.com")
TEST_CONNECT_FAIL(medium_com, "medium.com")
TEST_CONNECT_FAIL(amazon_com, "amazon.com")
TEST_CONNECT_FAIL(github_com, "github.com")
TEST_CONNECT_FAIL(wikimedia_org, "wikimedia.org")
TEST_CONNECT_FAIL(nih_gov, "nih.gov")
TEST_CONNECT_FAIL(news_google_com, "news.google.com")
TEST_CONNECT_FAIL(google_co_uk, "google.co.uk")
TEST_CONNECT_FAIL(mail_ru, "mail.ru")
TEST_CONNECT_FAIL(google_com_br, "google.com.br")
TEST_CONNECT_FAIL(imdb_com, "imdb.com")
TEST_CONNECT_FAIL(developers_google_com, "developers.google.com")
TEST_CONNECT_FAIL(google_co_jp, "google.co.jp")
TEST_CONNECT_FAIL(whatsapp_com, "whatsapp.com")
TEST_CONNECT_FAIL(www_yahoo_com, "www.yahoo.com")
TEST_CONNECT_FAIL(jimdofree_com, "jimdofree.com")
TEST_CONNECT_FAIL(networkadvertising_org, "networkadvertising.org")
TEST_CONNECT_FAIL(google_es, "google.es")
TEST_CONNECT_FAIL(google_de, "google.de")
TEST_CONNECT_FAIL(mail_google_com, "mail.google.com")
TEST_CONNECT_FAIL(w3_org, "w3.org")
TEST_CONNECT_FAIL(t_me, "t.me")
TEST_CONNECT_FAIL(dailymotion_com, "dailymotion.com")
TEST_CONNECT_FAIL(reuters_com, "reuters.com")
TEST_CONNECT_FAIL(myspace_com, "myspace.com")
TEST_CONNECT_FAIL(theguardian_com, "theguardian.com")
TEST_CONNECT_FAIL(live_com, "live.com")
TEST_CONNECT_FAIL(policies_google_com, "policies.google.com")
TEST_CONNECT_FAIL(dropbox_com, "dropbox.com")
TEST_CONNECT_FAIL(pt_wikipedia_org, "pt.wikipedia.org")
TEST_CONNECT_FAIL(google_fr, "google.fr")
TEST_CONNECT_FAIL(fr_wikipedia_org, "fr.wikipedia.org")
TEST_CONNECT_FAIL(uol_com_br, "uol.com.br")
TEST_CONNECT_FAIL(forbes_com, "forbes.com")
TEST_CONNECT_FAIL(feedburner_com, "feedburner.com")
TEST_CONNECT_FAIL(hugedomains_com, "hugedomains.com")
TEST_CONNECT_FAIL(bbc_com, "bbc.com")
TEST_CONNECT_FAIL(cnn_com, "cnn.com")
TEST_CONNECT_FAIL(who_int, "who.int")
TEST_CONNECT_FAIL(msn_com, "msn.com")
TEST_CONNECT_FAIL(slideshare_net, "slideshare.net")
TEST_CONNECT_FAIL(paypal_com, "paypal.com")
TEST_CONNECT_FAIL(gstatic_com, "gstatic.com")
TEST_CONNECT_FAIL(aliexpress_com, "aliexpress.com")
TEST_CONNECT_FAIL(photos_google_com, "photos.google.com")
TEST_CONNECT_FAIL(nytimes_com, "nytimes.com")
TEST_CONNECT_FAIL(globo_com, "globo.com")
TEST_CONNECT_FAIL(ok_ru, "ok.ru")
TEST_CONNECT_FAIL(bloomberg_com, "bloomberg.com")
TEST_CONNECT_FAIL(amazon_de, "amazon.de")
TEST_CONNECT_FAIL(harvard_edu, "harvard.edu")
TEST_CONNECT_FAIL(office_com, "office.com")
TEST_CONNECT_FAIL(draft_blogger_com, "draft.blogger.com")
TEST_CONNECT_FAIL(terra_com_br, "terra.com.br")
TEST_CONNECT_FAIL(huffingtonpost_com, "huffingtonpost.com")
TEST_CONNECT_FAIL(rt_com, "rt.com")
TEST_CONNECT_FAIL(amazon_co_jp, "amazon.co.jp")
TEST_CONNECT_FAIL(samsung_com, "samsung.com")
TEST_CONNECT_FAIL(ft_com, "ft.com")
TEST_CONNECT_FAIL(youronlinechoices_com, "youronlinechoices.com")
TEST_CONNECT_FAIL(tinyurl_com, "tinyurl.com")
TEST_CONNECT_FAIL(google_ru, "google.ru")
TEST_CONNECT_FAIL(cpanel_com, "cpanel.com")
TEST_CONNECT_FAIL(news_yahoo_com, "news.yahoo.com")
TEST_CONNECT_FAIL(bing_com, "bing.com")
TEST_CONNECT_FAIL(dailymail_co_uk, "dailymail.co.uk")
TEST_CONNECT_FAIL(foxnews_com, "foxnews.com")
TEST_CONNECT_FAIL(bit_ly, "bit.ly")
TEST_CONNECT_FAIL(abcnews_go_com, "abcnews.go.com")
TEST_CONNECT_FAIL(oracle_com, "oracle.com")
TEST_CONNECT_FAIL(picasaweb_google_com, "picasaweb.google.com")
TEST_CONNECT_FAIL(aol_com, "aol.com")
TEST_CONNECT_FAIL(washingtonpost_com, "washingtonpost.com")
TEST_CONNECT_FAIL(fb_com, "fb.com")
TEST_CONNECT_FAIL(telegram_me, "telegram.me")
TEST_CONNECT_FAIL(steampowered_com, "steampowered.com")
TEST_CONNECT_FAIL(amazon_co_uk, "amazon.co.uk")
TEST_CONNECT_FAIL(independent_co_uk, "independent.co.uk")
TEST_CONNECT_FAIL(wired_com, "wired.com")
TEST_CONNECT_FAIL(de_wikipedia_org, "de.wikipedia.org")
TEST_CONNECT_FAIL(android_com, "android.com")
TEST_CONNECT_FAIL(soundcloud_com, "soundcloud.com")
TEST_CONNECT_FAIL(wsj_com, "wsj.com")
TEST_CONNECT_FAIL(telegraph_co_uk, "telegraph.co.uk")
TEST_CONNECT_FAIL(businessinsider_com, "businessinsider.com")
TEST_CONNECT_FAIL(pinterest_com, "pinterest.com")
TEST_CONNECT_FAIL(hatena_ne_jp, "hatena.ne.jp")
TEST_CONNECT_FAIL(ipv4_google_com, "ipv4.google.com")
TEST_CONNECT_FAIL(files_wordpress_com, "files.wordpress.com")
TEST_CONNECT_FAIL(issuu_com, "issuu.com")
TEST_CONNECT_FAIL(ig_com_br, "ig.com.br")
TEST_CONNECT_FAIL(thesun_co_uk, "thesun.co.uk")
TEST_CONNECT_FAIL(translate_google_com, "translate.google.com")
TEST_CONNECT_FAIL(wikia_com, "wikia.com")
TEST_CONNECT_FAIL(mediafire_com, "mediafire.com")
TEST_CONNECT_FAIL(un_org, "un.org")
TEST_CONNECT_FAIL(webmd_com, "webmd.com")
TEST_CONNECT_FAIL(lefigaro_fr, "lefigaro.fr")
TEST_CONNECT_FAIL(picasa_google_com, "picasa.google.com")
TEST_CONNECT_FAIL(search_google_com, "search.google.com")
TEST_CONNECT_FAIL(themeforest_net, "themeforest.net")
TEST_CONNECT_FAIL(google_it, "google.it")
TEST_CONNECT_FAIL(get_google_com, "get.google.com")
TEST_CONNECT_FAIL(www_gov_uk, "www.gov.uk")
TEST_CONNECT_FAIL(usatoday_com, "usatoday.com")
TEST_CONNECT_FAIL(scribd_com, "scribd.com")
TEST_CONNECT_FAIL(archive_org, "archive.org")
TEST_CONNECT_FAIL(cdc_gov, "cdc.gov")
TEST_CONNECT_FAIL(code_google_com, "code.google.com")
TEST_CONNECT_FAIL(privacyshield_gov, "privacyshield.gov")
TEST_CONNECT_FAIL(fandom_com, "fandom.com")
TEST_CONNECT_FAIL(twitter_com, "twitter.com")
TEST_CONNECT_FAIL(books_google_com, "books.google.com")
TEST_CONNECT_FAIL(abril_com_br, "abril.com.br")
TEST_CONNECT_FAIL(cpanel_net, "cpanel.net")
TEST_CONNECT_FAIL(rakuten_co_jp, "rakuten.co.jp")
TEST_CONNECT_FAIL(www_wix_com, "www.wix.com")
TEST_CONNECT_FAIL(tools_google_com, "tools.google.com")
TEST_CONNECT_FAIL(buydomains_com, "buydomains.com")
TEST_CONNECT_FAIL(elpais_com, "elpais.com")
TEST_CONNECT_FAIL(cnet_com, "cnet.com")
TEST_CONNECT_FAIL(booking_com, "booking.com")
TEST_CONNECT_FAIL(nasa_gov, "nasa.gov")
TEST_CONNECT_FAIL(namecheap_com, "namecheap.com")
TEST_CONNECT_FAIL(sedo_com, "sedo.com")
TEST_CONNECT_FAIL(plesk_com, "plesk.com")
TEST_CONNECT_FAIL(goo_gl, "goo.gl")
TEST_CONNECT_FAIL(myaccount_google_com, "myaccount.google.com")
TEST_CONNECT_FAIL(aboutads_info, "aboutads.info")
TEST_CONNECT_FAIL(opera_com, "opera.com")
TEST_CONNECT_FAIL(ebay_com, "ebay.com")
TEST_CONNECT_FAIL(mirror_co_uk, "mirror.co.uk")
TEST_CONNECT_FAIL(marketingplatform_google_com, "marketingplatform.google.com")
TEST_CONNECT_FAIL(change_org, "change.org")
TEST_CONNECT_FAIL(gravatar_com, "gravatar.com")
TEST_CONNECT_FAIL(time_com, "time.com")
TEST_CONNECT_FAIL(walmart_com, "walmart.com")
TEST_CONNECT_FAIL(ign_com, "ign.com")
TEST_CONNECT_FAIL(bandcamp_com, "bandcamp.com")
TEST_CONNECT_FAIL(hm_com, "hm.com")
TEST_CONNECT_FAIL(m_wikipedia_org, "m.wikipedia.org")
TEST_CONNECT_FAIL(xbox_com, "xbox.com")
TEST_CONNECT_FAIL(depositfiles_com, "depositfiles.com")
TEST_CONNECT_FAIL(dell_com, "dell.com")
TEST_CONNECT_FAIL(wp_com, "wp.com")
TEST_CONNECT_FAIL(addthis_com, "addthis.com")
TEST_CONNECT_FAIL(stackoverflow_com, "stackoverflow.com")
TEST_CONNECT_FAIL(oup_com, "oup.com")
TEST_CONNECT_FAIL(amazon_es, "amazon.es")
TEST_CONNECT_FAIL(ietf_org, "ietf.org")
TEST_CONNECT_FAIL(hp_com, "hp.com")
TEST_CONNECT_FAIL(secureserver_net, "secureserver.net")
TEST_CONNECT_FAIL(photos1_blogger_com, "photos1.blogger.com")
TEST_CONNECT_FAIL(icann_org, "icann.org")
TEST_CONNECT_FAIL(abc_net_au, "abc.net.au")
TEST_CONNECT_FAIL(yadi_sk, "yadi.sk")
TEST_CONNECT_FAIL(techcrunch_com, "techcrunch.com")
TEST_CONNECT_FAIL(nhk_or_jp, "nhk.or.jp")
TEST_CONNECT_FAIL(nginx_org, "nginx.org")
TEST_CONNECT_FAIL(buzzfeed_com, "buzzfeed.com")
TEST_CONNECT_FAIL(britannica_com, "britannica.com")
TEST_CONNECT_FAIL(bp3_blogger_com, "bp3.blogger.com")
TEST_CONNECT_FAIL(hollywoodreporter_com, "hollywoodreporter.com")
TEST_CONNECT_FAIL(scoop_it, "scoop.it")
TEST_CONNECT_FAIL(biglobe_ne_jp, "biglobe.ne.jp")
TEST_CONNECT_FAIL(trustpilot_com, "trustpilot.com")
TEST_CONNECT_FAIL(huffpost_com, "huffpost.com")
TEST_CONNECT_FAIL(forms_gle, "forms.gle")
TEST_CONNECT_FAIL(a8_net, "a8.net")
TEST_CONNECT_FAIL(lemonde_fr, "lemonde.fr")
TEST_CONNECT_FAIL(npr_org, "npr.org")
TEST_CONNECT_FAIL(guardian_co_uk, "guardian.co.uk")
TEST_CONNECT_FAIL(spotify_com, "spotify.com")
TEST_CONNECT_FAIL(amazon_it, "amazon.it")
TEST_CONNECT_FAIL(ria_ru, "ria.ru")
TEST_CONNECT_FAIL(ted_com, "ted.com")
TEST_CONNECT_FAIL(imageshack_us, "imageshack.us")
TEST_CONNECT_FAIL(kickstarter_com, "kickstarter.com")
TEST_CONNECT_FAIL(list_manage_com, "list-manage.com")
TEST_CONNECT_FAIL(columbia_edu, "columbia.edu")
TEST_CONNECT_FAIL(gnu_org, "gnu.org")
TEST_CONNECT_FAIL(google_nl, "google.nl")
TEST_CONNECT_FAIL(playstation_com, "playstation.com")
TEST_CONNECT_FAIL(repubblica_it, "repubblica.it")
TEST_CONNECT_FAIL(cbsnews_com, "cbsnews.com")
TEST_CONNECT_FAIL(my_yahoo_com, "my.yahoo.com")
TEST_CONNECT_FAIL(ibm_com, "ibm.com")
TEST_CONNECT_FAIL(dan_com, "dan.com")
TEST_CONNECT_FAIL(urbandictionary_com, "urbandictionary.com")
TEST_CONNECT_FAIL(sciencedaily_com, "sciencedaily.com")
TEST_CONNECT_FAIL(google_com_tw, "google.com.tw")
TEST_CONNECT_FAIL(bloglovin_com, "bloglovin.com")
TEST_CONNECT_FAIL(yelp_com, "yelp.com")
TEST_CONNECT_FAIL(elmundo_es, "elmundo.es")
TEST_CONNECT_FAIL(amazon_fr, "amazon.fr")
TEST_CONNECT_FAIL(umich_edu, "umich.edu")
TEST_CONNECT_FAIL(news_com_au, "news.com.au")
TEST_CONNECT_FAIL(bp1_blogger_com, "bp1.blogger.com")
TEST_CONNECT_FAIL(naver_jp, "naver.jp")
TEST_CONNECT_FAIL(disqus_com, "disqus.com")
TEST_CONNECT_FAIL(theatlantic_com, "theatlantic.com")
TEST_CONNECT_FAIL(finance_yahoo_com, "finance.yahoo.com")
TEST_CONNECT_FAIL(loc_gov, "loc.gov")
TEST_CONNECT_FAIL(php_net, "php.net")
TEST_CONNECT_FAIL(cbc_ca, "cbc.ca")
TEST_CONNECT_FAIL(www_over_blog_com, "www.over-blog.com")
TEST_CONNECT_FAIL(ggpht_com, "ggpht.com")
TEST_CONNECT_FAIL(pixabay_com, "pixabay.com")
TEST_CONNECT_FAIL(yandex_ru, "yandex.ru")
TEST_CONNECT_FAIL(cisco_com, "cisco.com")
TEST_CONNECT_FAIL(parallels_com, "parallels.com")
TEST_CONNECT_FAIL(dw_com, "dw.com")
TEST_CONNECT_FAIL(pexels_com, "pexels.com")
TEST_CONNECT_FAIL(addtoany_com, "addtoany.com")
TEST_CONNECT_FAIL(lg_com, "lg.com")
TEST_CONNECT_FAIL(storage_googleapis_com, "storage.googleapis.com")
TEST_CONNECT_FAIL(quora_com, "quora.com")
TEST_CONNECT_FAIL(netflix_com, "netflix.com")
TEST_CONNECT_FAIL(tes_com, "tes.com")
TEST_CONNECT_FAIL(gizmodo_com, "gizmodo.com")
TEST_CONNECT_FAIL(orkut_com_br, "orkut.com.br")
TEST_CONNECT_FAIL(weibo_com, "weibo.com")
TEST_CONNECT_FAIL(000webhost_com, "000webhost.com")
TEST_CONNECT_FAIL(nypost_com, "nypost.com")
TEST_CONNECT_FAIL(ja_wikipedia_org, "ja.wikipedia.org")
TEST_CONNECT_FAIL(express_co_uk, "express.co.uk")
TEST_CONNECT_FAIL(marriott_com, "marriott.com")
TEST_CONNECT_FAIL(newsweek_com, "newsweek.com")
TEST_CONNECT_FAIL(mozilla_com, "mozilla.com")
TEST_CONNECT_FAIL(noaa_gov, "noaa.gov")
TEST_CONNECT_FAIL(imageshack_com, "imageshack.com")
TEST_CONNECT_FAIL(bp2_blogger_com, "bp2.blogger.com")
TEST_CONNECT_FAIL(google_co_in, "google.co.in")
TEST_CONNECT_FAIL(worldbank_org, "worldbank.org")
TEST_CONNECT_FAIL(windowsphone_com, "windowsphone.com")
TEST_CONNECT_FAIL(ovh_net, "ovh.net")
TEST_CONNECT_FAIL(bt_com, "bt.com")
TEST_CONNECT_FAIL(sapo_pt, "sapo.pt")
TEST_CONNECT_FAIL(goodreads_com, "goodreads.com")
TEST_CONNECT_FAIL(vice_com, "vice.com")
TEST_CONNECT_FAIL(xinhuanet_com, "xinhuanet.com")
TEST_CONNECT_FAIL(over_blog_kiwi_com, "over-blog-kiwi.com")
TEST_CONNECT_FAIL(researchgate_net, "researchgate.net")
TEST_CONNECT_FAIL(economist_com, "economist.com")
TEST_CONNECT_FAIL(ovh_co_uk, "ovh.co.uk")
TEST_CONNECT_FAIL(digg_com, "digg.com")
TEST_CONNECT_FAIL(instagram_com, "instagram.com")
TEST_CONNECT_FAIL(photobucket_com, "photobucket.com")
TEST_CONNECT_FAIL(usnews_com, "usnews.com")
TEST_CONNECT_FAIL(mega_nz, "mega.nz")
TEST_CONNECT_FAIL(alibaba_com, "alibaba.com")
TEST_CONNECT_FAIL(mashable_com, "mashable.com")
TEST_CONNECT_FAIL(deezer_com, "deezer.com")
TEST_CONNECT_FAIL(asus_com, "asus.com")
TEST_CONNECT_FAIL(nginx_com, "nginx.com")
TEST_CONNECT_FAIL(iubenda_com, "iubenda.com")
TEST_CONNECT_FAIL(netvibes_com, "netvibes.com")
TEST_CONNECT_FAIL(pl_wikipedia_org, "pl.wikipedia.org")
TEST_CONNECT_FAIL(qq_com, "qq.com")
TEST_CONNECT_FAIL(yale_edu, "yale.edu")
TEST_CONNECT_FAIL(bitly_com, "bitly.com")
TEST_CONNECT_FAIL(espn_com, "espn.com")
TEST_CONNECT_FAIL(pbs_org, "pbs.org")
TEST_CONNECT_FAIL(doubleclick_net, "doubleclick.net")
TEST_CONNECT_FAIL(sciencemag_org, "sciencemag.org")
TEST_CONNECT_FAIL(rapidshare_com, "rapidshare.com")
TEST_CONNECT_FAIL(nydailynews_com, "nydailynews.com")
TEST_CONNECT_FAIL(indiatimes_com, "indiatimes.com")
TEST_CONNECT_FAIL(google_pl, "google.pl")
TEST_CONNECT_FAIL(ikea_com, "ikea.com")
TEST_CONNECT_FAIL(blackberry_com, "blackberry.com")
TEST_CONNECT_FAIL(naver_com, "naver.com")
TEST_CONNECT_FAIL(google_co_id, "google.co.id")
TEST_CONNECT_FAIL(4shared_com, "4shared.com")
TEST_CONNECT_FAIL(nbcnews_com, "nbcnews.com")
TEST_CONNECT_FAIL(shopify_com, "shopify.com")
TEST_CONNECT_FAIL(welt_de, "welt.de")
TEST_CONNECT_FAIL(asahi_com, "asahi.com")
TEST_CONNECT_FAIL(ea_com, "ea.com")
TEST_CONNECT_FAIL(princeton_edu, "princeton.edu")
TEST_CONNECT_FAIL(latimes_com, "latimes.com")
TEST_CONNECT_FAIL(mit_edu, "mit.edu")
TEST_CONNECT_FAIL(t_co, "t.co")
TEST_CONNECT_FAIL(nvidia_com, "nvidia.com")
TEST_CONNECT_FAIL(cambridge_org, "cambridge.org")
TEST_CONNECT_FAIL(disney_com, "disney.com")
TEST_CONNECT_FAIL(sciencedirect_com, "sciencedirect.com")
TEST_CONNECT_FAIL(eventbrite_com, "eventbrite.com")
TEST_CONNECT_FAIL(vox_com, "vox.com")
TEST_CONNECT_FAIL(engadget_com, "engadget.com")
TEST_CONNECT_FAIL(unesco_org, "unesco.org")
TEST_CONNECT_FAIL(wikihow_com, "wikihow.com")
TEST_CONNECT_FAIL(goo_ne_jp, "goo.ne.jp")
TEST_CONNECT_FAIL(ox_ac_uk, "ox.ac.uk")
TEST_CONNECT_FAIL(gmail_com, "gmail.com")
TEST_CONNECT_FAIL(thetimes_co_uk, "thetimes.co.uk")
TEST_CONNECT_FAIL(nikkei_com, "nikkei.com")
TEST_CONNECT_FAIL(stanford_edu, "stanford.edu")
TEST_CONNECT_FAIL(metro_co_uk, "metro.co.uk")
TEST_CONNECT_FAIL(tripadvisor_com, "tripadvisor.com")
TEST_CONNECT_FAIL(smh_com_au, "smh.com.au")
TEST_CONNECT_FAIL(mystrikingly_com, "mystrikingly.com")
TEST_CONNECT_FAIL(mysql_com, "mysql.com")
TEST_CONNECT_FAIL(rambler_ru, "rambler.ru")
TEST_CONNECT_FAIL(twitch_tv, "twitch.tv")
TEST_CONNECT_FAIL(it_wikipedia_org, "it.wikipedia.org")
TEST_CONNECT_FAIL(cornell_edu, "cornell.edu")
TEST_CONNECT_FAIL(channel4_com, "channel4.com")
TEST_CONNECT_FAIL(gofundme_com, "gofundme.com")
TEST_CONNECT_FAIL(e_recht24_de, "e-recht24.de")
TEST_CONNECT_FAIL(instructables_com, "instructables.com")
TEST_CONNECT_FAIL(berkeley_edu, "berkeley.edu")
TEST_CONNECT_FAIL(ru_wikipedia_org, "ru.wikipedia.org")
TEST_CONNECT_FAIL(www_weebly_com, "www.weebly.com")
TEST_CONNECT_FAIL(nokia_com, "nokia.com")
TEST_CONNECT_FAIL(standard_co_uk, "standard.co.uk")
TEST_CONNECT_FAIL(groups_google_com, "groups.google.com")
TEST_CONNECT_FAIL(www_wikipedia_org, "www.wikipedia.org")
TEST_CONNECT_FAIL(akamaihd_net, "akamaihd.net")
TEST_CONNECT_FAIL(whitehouse_gov, "whitehouse.gov")
TEST_CONNECT_FAIL(sfgate_com, "sfgate.com")
TEST_CONNECT_FAIL(academia_edu, "academia.edu")
TEST_CONNECT_FAIL(shutterstock_com, "shutterstock.com")
TEST_CONNECT_FAIL(psychologytoday_com, "psychologytoday.com")
TEST_CONNECT_FAIL(target_com, "target.com")
TEST_CONNECT_FAIL(id_wikipedia_org, "id.wikipedia.org")
TEST_CONNECT_FAIL(ytimg_com, "ytimg.com")
TEST_CONNECT_FAIL(box_com, "box.com")
TEST_CONNECT_FAIL(adssettings_google_com, "adssettings.google.com")
TEST_CONNECT_FAIL(rtve_es, "rtve.es")
TEST_CONNECT_FAIL(washington_edu, "washington.edu")
TEST_CONNECT_FAIL(apache_org, "apache.org")
TEST_CONNECT_FAIL(wa_me, "wa.me")
TEST_CONNECT_FAIL(nature_com, "nature.com")
TEST_CONNECT_FAIL(cnbc_com, "cnbc.com")
TEST_CONNECT_FAIL(godaddy_com, "godaddy.com")
TEST_CONNECT_FAIL(bp0_blogger_com, "bp0.blogger.com")
TEST_CONNECT_FAIL(wiley_com, "wiley.com")
TEST_CONNECT_FAIL(sendspace_com, "sendspace.com")
TEST_CONNECT_FAIL(nationalgeographic_com, "nationalgeographic.com")
TEST_CONNECT_FAIL(fifa_com, "fifa.com")
TEST_CONNECT_FAIL(abc_es, "abc.es")
TEST_CONNECT_FAIL(google_ca, "google.ca")
TEST_CONNECT_FAIL(zendesk_com, "zendesk.com")
TEST_CONNECT_FAIL(spiegel_de, "spiegel.de")
TEST_CONNECT_FAIL(utexas_edu, "utexas.edu")
TEST_CONNECT_FAIL(theverge_com, "theverge.com")
TEST_CONNECT_FAIL(about_com, "about.com")
TEST_CONNECT_FAIL(surveymonkey_com, "surveymonkey.com")
TEST_CONNECT_FAIL(variety_com, "variety.com")
TEST_CONNECT_FAIL(ovh_com, "ovh.com")
TEST_CONNECT_FAIL(googleblog_com, "googleblog.com")
TEST_CONNECT_FAIL(fastcompany_com, "fastcompany.com")
TEST_CONNECT_FAIL(yahoo_co_jp, "yahoo.co.jp")
TEST_CONNECT_FAIL(www_livejournal_com, "www.livejournal.com")
TEST_CONNECT_FAIL(ap_org, "ap.org")
TEST_CONNECT_FAIL(nicovideo_jp, "nicovideo.jp")
TEST_CONNECT_FAIL(marketwatch_com, "marketwatch.com")
TEST_CONNECT_FAIL(excite_co_jp, "excite.co.jp")
TEST_CONNECT_FAIL(stuff_co_nz, "stuff.co.nz")
TEST_CONNECT_FAIL(weforum_org, "weforum.org")
TEST_CONNECT_FAIL(so_net_ne_jp, "so-net.ne.jp")
TEST_CONNECT_FAIL(history_com, "history.com")
TEST_CONNECT_FAIL(amazon_in, "amazon.in")
TEST_CONNECT_FAIL(gooyaabitemplates_com, "gooyaabitemplates.com")
TEST_CONNECT_FAIL(evernote_com, "evernote.com")
TEST_CONNECT_FAIL(intel_com, "intel.com")
TEST_CONNECT_FAIL(airbnb_com, "airbnb.com")
TEST_CONNECT_FAIL(house_gov, "house.gov")
TEST_CONNECT_FAIL(cbslocal_com, "cbslocal.com")
TEST_CONNECT_FAIL(mhlw_go_jp, "mhlw.go.jp")
TEST_CONNECT_FAIL(rottentomatoes_com, "rottentomatoes.com")
TEST_CONNECT_FAIL(cam_ac_uk, "cam.ac.uk")
TEST_CONNECT_FAIL(mail_yahoo_com, "mail.yahoo.com")
TEST_CONNECT_FAIL(prnewswire_com, "prnewswire.com")
TEST_CONNECT_FAIL(jstor_org, "jstor.org")
TEST_CONNECT_FAIL(sputniknews_com, "sputniknews.com")
TEST_CONNECT_FAIL(soratemplates_com, "soratemplates.com")
TEST_CONNECT_FAIL(archives_gov, "archives.gov")
TEST_CONNECT_FAIL(disney_go_com, "disney.go.com")
TEST_CONNECT_FAIL(behance_net, "behance.net")
TEST_CONNECT_FAIL(newscientist_com, "newscientist.com")
TEST_CONNECT_FAIL(teamviewer_com, "teamviewer.com")
TEST_CONNECT_FAIL(thestar_com, "thestar.com")
TEST_CONNECT_FAIL(debian_org, "debian.org")
TEST_CONNECT_FAIL(sina_com_cn, "sina.com.cn")
TEST_CONNECT_FAIL(allrecipes_com, "allrecipes.com")
TEST_CONNECT_FAIL(eonline_com, "eonline.com")
TEST_CONNECT_FAIL(ndtv_com, "ndtv.com")
TEST_CONNECT_FAIL(greenpeace_org, "greenpeace.org")
TEST_CONNECT_FAIL(indiegogo_com, "indiegogo.com")
TEST_CONNECT_FAIL(fda_gov, "fda.gov")
TEST_CONNECT_FAIL(cmu_edu, "cmu.edu")
TEST_CONNECT_FAIL(pcmag_com, "pcmag.com")
TEST_CONNECT_FAIL(ehow_com, "ehow.com")
TEST_CONNECT_FAIL(discovery_com, "discovery.com")
TEST_CONNECT_FAIL(ask_fm, "ask.fm")
TEST_CONNECT_FAIL(biblegateway_com, "biblegateway.com")
TEST_CONNECT_FAIL(narod_ru, "narod.ru")
TEST_CONNECT_FAIL(foursquare_com, "foursquare.com")
TEST_CONNECT_FAIL(slate_com, "slate.com")
TEST_CONNECT_FAIL(csmonitor_com, "csmonitor.com")
TEST_CONNECT_FAIL(daum_net, "daum.net")
TEST_CONNECT_FAIL(axs_com, "axs.com")
TEST_CONNECT_FAIL(fortune_com, "fortune.com")
TEST_CONNECT_FAIL(bund_de, "bund.de")
TEST_CONNECT_FAIL(feedproxy_google_com, "feedproxy.google.com")
TEST_CONNECT_FAIL(gutenberg_org, "gutenberg.org")
TEST_CONNECT_FAIL(espn_go_com, "espn.go.com")
TEST_CONNECT_FAIL(ubuntu_com, "ubuntu.com")
TEST_CONNECT_FAIL(merriam_webster_com, "merriam-webster.com")
TEST_CONNECT_FAIL(unicef_org, "unicef.org")
TEST_CONNECT_FAIL(softpedia_com, "softpedia.com")
TEST_CONNECT_FAIL(techradar_com, "techradar.com")
TEST_CONNECT_FAIL(dribbble_com, "dribbble.com")
TEST_CONNECT_FAIL(e_monsite_com, "e-monsite.com")
TEST_CONNECT_FAIL(wiktionary_org, "wiktionary.org")
TEST_CONNECT_FAIL(usc_edu, "usc.edu")
TEST_CONNECT_FAIL(alexa_com, "alexa.com")
TEST_CONNECT_FAIL(usgs_gov, "usgs.gov")
TEST_CONNECT_FAIL(outlook_com, "outlook.com")
TEST_CONNECT_FAIL(20minutos_es, "20minutos.es")
TEST_CONNECT_FAIL(psu_edu, "psu.edu")
TEST_CONNECT_FAIL(scientificamerican_com, "scientificamerican.com")
TEST_CONNECT_FAIL(amazon_ca, "amazon.ca")
TEST_CONNECT_FAIL(newyorker_com, "newyorker.com")
TEST_CONNECT_FAIL(viagens_com_br, "viagens.com.br")
TEST_CONNECT_FAIL(politico_com, "politico.com")
TEST_CONNECT_FAIL(com_com, "com.com")
TEST_CONNECT_FAIL(www_skyrock_com, "www.skyrock.com")
TEST_CONNECT_FAIL(thedailybeast_com, "thedailybeast.com")
TEST_CONNECT_FAIL(xing_com, "xing.com")
TEST_CONNECT_FAIL(ieee_org, "ieee.org")
TEST_CONNECT_FAIL(statista_com, "statista.com")
TEST_CONNECT_FAIL(consumerreports_org, "consumerreports.org")
TEST_CONNECT_FAIL(lonelyplanet_com, "lonelyplanet.com")
TEST_CONNECT_FAIL(weather_com, "weather.com")
TEST_CONNECT_FAIL(blog_fc2_com, "blog.fc2.com")
TEST_CONNECT_FAIL(gesetze_im_internet_de, "gesetze-im-internet.de")
TEST_CONNECT_FAIL(zdnet_com, "zdnet.com")
TEST_CONNECT_FAIL(chicagotribune_com, "chicagotribune.com")
TEST_CONNECT_FAIL(etsy_com, "etsy.com")
TEST_CONNECT_FAIL(interia_pl, "interia.pl")
TEST_CONNECT_FAIL(tabelog_com, "tabelog.com")
TEST_CONNECT_FAIL(discord_gg, "discord.gg")
TEST_CONNECT_FAIL(answers_com, "answers.com")
TEST_CONNECT_FAIL(search_yahoo_com, "search.yahoo.com")
TEST_CONNECT_FAIL(amzn_to, "amzn.to")
TEST_CONNECT_FAIL(dictionary_com, "dictionary.com")
TEST_CONNECT_FAIL(answers_yahoo_com, "answers.yahoo.com")
TEST_CONNECT_FAIL(ftc_gov, "ftc.gov")
TEST_CONNECT_FAIL(sakura_ne_jp, "sakura.ne.jp")
TEST_CONNECT_FAIL(www_nhs_uk, "www.nhs.uk")
TEST_CONNECT_FAIL(sky_com, "sky.com")
TEST_CONNECT_FAIL(thenextweb_com, "thenextweb.com")
TEST_CONNECT_FAIL(livescience_com, "livescience.com")
TEST_CONNECT_FAIL(autodesk_com, "autodesk.com")
TEST_CONNECT_FAIL(example_com, "example.com")
TEST_CONNECT_FAIL(uber_com, "uber.com")
TEST_CONNECT_FAIL(businesswire_com, "businesswire.com")
TEST_CONNECT_FAIL(salon_com, "salon.com")
TEST_CONNECT_FAIL(cia_gov, "cia.gov")
TEST_CONNECT_FAIL(redhat_com, "redhat.com")
TEST_CONNECT_FAIL(chinadaily_com_cn, "chinadaily.com.cn")
TEST_CONNECT_FAIL(kinja_com, "kinja.com")
TEST_CONNECT_FAIL(megaupload_com, "megaupload.com")
TEST_CONNECT_FAIL(khanacademy_org, "khanacademy.org")
TEST_CONNECT_FAIL(ameblo_jp, "ameblo.jp")
TEST_CONNECT_FAIL(plos_org, "plos.org")
TEST_CONNECT_FAIL(ebay_co_uk, "ebay.co.uk")
































