#include <gtest/gtest.h>

#include <future>
#include <stdlib.h>
#include <string>

#include "timeouts.h"

extern "C" { // To indicate that the code is C code when linking--important

#include "helper_functions.h"

const char* ERR_SOURCE_CONNECT = "connect()";
const char* ERR_SOURCE_HOSTNAME = "TLS_HOSTNAME getsockopt()";
#define HTTPS_PORT "443"

}

#define RUN_TEST(testname, hostname_str)                            \
    TEST(BadSSLTests, testname) {                                   \
                                                                    \
        TEST_TIMEOUT_BEGIN                                          \
                                                                    \
        const int NO_ERRNO = 0;                                     \
        struct sockaddr* addr;                                      \
        socklen_t addrlen;                                          \
        std::string hostname = hostname_str;                        \
        std::string port = HTTPS_PORT;                              \
        int dns_failed;                                             \
        int fd;                                                     \
                                                                    \
                                                                    \
        dns_failed = resolve_dns(hostname.c_str(),                  \
                    port.c_str(), &addr, &addrlen);                 \
        ASSERT_EQ(dns_failed, 0);                                   \
                                                                    \
        fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TLS);             \
        int socket_errno = errno;                                   \
        if (fd == -1)                                               \
            perror("socket creation failed");                       \
                                                                    \
        EXPECT_EQ(socket_errno, 0);                                 \
        ASSERT_GE(fd, 0);                                           \
                                                                    \
        int hostname_ret = setsockopt(fd, IPPROTO_TLS,              \
                TLS_HOSTNAME, hostname.c_str(), hostname.size()+1); \
        int hostname_errno = errno;                                 \
        if (hostname_ret != 0)                                      \
            print_socket_error(fd, ERR_SOURCE_HOSTNAME);            \
                                                                    \
        EXPECT_EQ(hostname_errno, 0);                               \
        ASSERT_EQ(hostname_ret, 0);                                 \
                                                                    \
        int connect_ret = connect(fd, addr, addrlen);               \
        int connect_errno = errno;                                  \
                                                                    \
        if (connect_ret != 0)                                       \
            print_socket_error(fd, ERR_SOURCE_CONNECT);             \
                                                                    \
        EXPECT_EQ(connect_errno, NO_ERRNO);                         \
        ASSERT_EQ(connect_ret, 0);                                  \
                                                                    \
        free(addr);                                                 \
        close(fd);                                                  \
                                                                    \
        TEST_TIMEOUT_FAIL_END(TIMEOUT_LONG)                         \
                                                                    \
    }




class Top500WebsitesTest : public testing::Test {
public:
    char *resp;
    int resp_len;
    int result;

    virtual void SetUp() {
        resp = NULL;
        resp_len = 0;
        result = 0;
    }

    virtual void TearDown() { }
};

/* top 500 websites per `moz.com` */

RUN_TEST(www_google_com, "www.google.com")
RUN_TEST(apple_com, "apple.com")
RUN_TEST(youtube_com, "youtube.com")
RUN_TEST(play_google_com, "play.google.com")
RUN_TEST(docs_google_com, "docs.google.com")
RUN_TEST(microsoft_com, "microsoft.com")
RUN_TEST(support_google_com, "support.google.com")
RUN_TEST(www_blogger_com, "www.blogger.com")
RUN_TEST(linkedin_com, "linkedin.com")
RUN_TEST(plus_google_com, "plus.google.com")
RUN_TEST(maps_google_com, "maps.google.com")
RUN_TEST(adobe_com, "adobe.com")
RUN_TEST(cloudflare_com, "cloudflare.com")
RUN_TEST(wordpress_org, "wordpress.org")
RUN_TEST(en_wikipedia_org, "en.wikipedia.org")
RUN_TEST(accounts_google_com, "accounts.google.com")
RUN_TEST(europa_eu, "europa.eu")
RUN_TEST(sites_google_com, "sites.google.com")
RUN_TEST(googleusercontent_com, "googleusercontent.com")
RUN_TEST(vimeo_com, "vimeo.com")
RUN_TEST(drive_google_com, "drive.google.com")
RUN_TEST(mozilla_org, "mozilla.org")
RUN_TEST(youtu_be, "youtu.be")
RUN_TEST(line_me, "line.me")
RUN_TEST(istockphoto_com, "istockphoto.com")
RUN_TEST(es_wikipedia_org, "es.wikipedia.org")
RUN_TEST(bp_blogspot_com, "bp.blogspot.com")
RUN_TEST(facebook_com, "facebook.com")
RUN_TEST(bbc_co_uk, "bbc.co.uk")
RUN_TEST(creativecommons_org, "creativecommons.org")
RUN_TEST(vk_com, "vk.com")
RUN_TEST(medium_com, "medium.com")
RUN_TEST(amazon_com, "amazon.com")
RUN_TEST(github_com, "github.com")
RUN_TEST(wikimedia_org, "wikimedia.org")
RUN_TEST(nih_gov, "nih.gov")
RUN_TEST(news_google_com, "news.google.com")
RUN_TEST(google_co_uk, "google.co.uk")
RUN_TEST(mail_ru, "mail.ru")
RUN_TEST(google_com_br, "google.com.br")
RUN_TEST(imdb_com, "imdb.com")
RUN_TEST(developers_google_com, "developers.google.com")
RUN_TEST(google_co_jp, "google.co.jp")
RUN_TEST(whatsapp_com, "whatsapp.com")
RUN_TEST(www_yahoo_com, "www.yahoo.com")
RUN_TEST(jimdofree_com, "jimdofree.com")
RUN_TEST(networkadvertising_org, "networkadvertising.org")
RUN_TEST(google_es, "google.es")
RUN_TEST(google_de, "google.de")
RUN_TEST(mail_google_com, "mail.google.com")
RUN_TEST(w3_org, "w3.org")
RUN_TEST(t_me, "t.me")
RUN_TEST(dailymotion_com, "dailymotion.com")
RUN_TEST(reuters_com, "reuters.com")
RUN_TEST(myspace_com, "myspace.com")
RUN_TEST(theguardian_com, "theguardian.com")
RUN_TEST(live_com, "live.com")
RUN_TEST(policies_google_com, "policies.google.com")
RUN_TEST(dropbox_com, "dropbox.com")
RUN_TEST(pt_wikipedia_org, "pt.wikipedia.org")
RUN_TEST(google_fr, "google.fr")
RUN_TEST(fr_wikipedia_org, "fr.wikipedia.org")
RUN_TEST(uol_com_br, "uol.com.br")
RUN_TEST(forbes_com, "forbes.com")
RUN_TEST(feedburner_com, "feedburner.com")
RUN_TEST(hugedomains_com, "hugedomains.com")
RUN_TEST(bbc_com, "bbc.com")
RUN_TEST(cnn_com, "cnn.com")
RUN_TEST(who_int, "who.int")
RUN_TEST(msn_com, "msn.com")
RUN_TEST(slideshare_net, "slideshare.net")
RUN_TEST(paypal_com, "paypal.com")
RUN_TEST(gstatic_com, "gstatic.com")
RUN_TEST(aliexpress_com, "aliexpress.com")
RUN_TEST(photos_google_com, "photos.google.com")
RUN_TEST(nytimes_com, "nytimes.com")
RUN_TEST(globo_com, "globo.com")
RUN_TEST(ok_ru, "ok.ru")
RUN_TEST(bloomberg_com, "bloomberg.com")
RUN_TEST(amazon_de, "amazon.de")
RUN_TEST(harvard_edu, "harvard.edu")
RUN_TEST(office_com, "office.com")
RUN_TEST(draft_blogger_com, "draft.blogger.com")
RUN_TEST(terra_com_br, "terra.com.br")
RUN_TEST(huffingtonpost_com, "huffingtonpost.com")
RUN_TEST(rt_com, "rt.com")
RUN_TEST(amazon_co_jp, "amazon.co.jp")
RUN_TEST(samsung_com, "samsung.com")
RUN_TEST(ft_com, "ft.com")
RUN_TEST(youronlinechoices_com, "youronlinechoices.com")
RUN_TEST(tinyurl_com, "tinyurl.com")
RUN_TEST(google_ru, "google.ru")
RUN_TEST(cpanel_com, "cpanel.com")
RUN_TEST(news_yahoo_com, "news.yahoo.com")
RUN_TEST(bing_com, "bing.com")
RUN_TEST(dailymail_co_uk, "dailymail.co.uk")
RUN_TEST(foxnews_com, "foxnews.com")
RUN_TEST(bit_ly, "bit.ly")
RUN_TEST(abcnews_go_com, "abcnews.go.com")
RUN_TEST(oracle_com, "oracle.com")
RUN_TEST(picasaweb_google_com, "picasaweb.google.com")
RUN_TEST(aol_com, "aol.com")
RUN_TEST(washingtonpost_com, "washingtonpost.com")
RUN_TEST(fb_com, "fb.com")
RUN_TEST(telegram_me, "telegram.me")
RUN_TEST(steampowered_com, "steampowered.com")
RUN_TEST(amazon_co_uk, "amazon.co.uk")
RUN_TEST(independent_co_uk, "independent.co.uk")
RUN_TEST(wired_com, "wired.com")
RUN_TEST(de_wikipedia_org, "de.wikipedia.org")
RUN_TEST(android_com, "android.com")
RUN_TEST(soundcloud_com, "soundcloud.com")
RUN_TEST(wsj_com, "wsj.com")
RUN_TEST(telegraph_co_uk, "telegraph.co.uk")
RUN_TEST(businessinsider_com, "businessinsider.com")
RUN_TEST(pinterest_com, "pinterest.com")
RUN_TEST(hatena_ne_jp, "hatena.ne.jp")
RUN_TEST(ipv4_google_com, "ipv4.google.com")
RUN_TEST(files_wordpress_com, "files.wordpress.com")
RUN_TEST(issuu_com, "issuu.com")
RUN_TEST(ig_com_br, "ig.com.br")
RUN_TEST(thesun_co_uk, "thesun.co.uk")
RUN_TEST(translate_google_com, "translate.google.com")
RUN_TEST(wikia_com, "wikia.com")
RUN_TEST(mediafire_com, "mediafire.com")
RUN_TEST(un_org, "un.org")
RUN_TEST(webmd_com, "webmd.com")
RUN_TEST(lefigaro_fr, "lefigaro.fr")
RUN_TEST(picasa_google_com, "picasa.google.com")
RUN_TEST(search_google_com, "search.google.com")
RUN_TEST(themeforest_net, "themeforest.net")
RUN_TEST(google_it, "google.it")
RUN_TEST(get_google_com, "get.google.com")
RUN_TEST(www_gov_uk, "www.gov.uk")
RUN_TEST(usatoday_com, "usatoday.com")
RUN_TEST(scribd_com, "scribd.com")
RUN_TEST(archive_org, "archive.org")
RUN_TEST(cdc_gov, "cdc.gov")
RUN_TEST(code_google_com, "code.google.com")
RUN_TEST(privacyshield_gov, "privacyshield.gov")
RUN_TEST(fandom_com, "fandom.com")
RUN_TEST(twitter_com, "twitter.com")
RUN_TEST(books_google_com, "books.google.com")
RUN_TEST(abril_com_br, "abril.com.br")
RUN_TEST(cpanel_net, "cpanel.net")
RUN_TEST(rakuten_co_jp, "rakuten.co.jp")
RUN_TEST(www_wix_com, "www.wix.com")
RUN_TEST(tools_google_com, "tools.google.com")
RUN_TEST(buydomains_com, "buydomains.com")
RUN_TEST(elpais_com, "elpais.com")
RUN_TEST(cnet_com, "cnet.com")
RUN_TEST(booking_com, "booking.com")
RUN_TEST(nasa_gov, "nasa.gov")
RUN_TEST(namecheap_com, "namecheap.com")
RUN_TEST(sedo_com, "sedo.com")
RUN_TEST(plesk_com, "plesk.com")
RUN_TEST(goo_gl, "goo.gl")
RUN_TEST(myaccount_google_com, "myaccount.google.com")
RUN_TEST(aboutads_info, "aboutads.info")
RUN_TEST(opera_com, "opera.com")
RUN_TEST(ebay_com, "ebay.com")
RUN_TEST(mirror_co_uk, "mirror.co.uk")
RUN_TEST(marketingplatform_google_com, "marketingplatform.google.com")
RUN_TEST(change_org, "change.org")
RUN_TEST(gravatar_com, "gravatar.com")
RUN_TEST(time_com, "time.com")
RUN_TEST(walmart_com, "walmart.com")
RUN_TEST(ign_com, "ign.com")
RUN_TEST(bandcamp_com, "bandcamp.com")
RUN_TEST(hm_com, "hm.com")
RUN_TEST(m_wikipedia_org, "m.wikipedia.org")
RUN_TEST(xbox_com, "xbox.com")
RUN_TEST(depositfiles_com, "depositfiles.com")
RUN_TEST(dell_com, "dell.com")
RUN_TEST(wp_com, "wp.com")
RUN_TEST(addthis_com, "addthis.com")
RUN_TEST(stackoverflow_com, "stackoverflow.com")
RUN_TEST(oup_com, "oup.com")
RUN_TEST(amazon_es, "amazon.es")
RUN_TEST(ietf_org, "ietf.org")
RUN_TEST(hp_com, "hp.com")
RUN_TEST(secureserver_net, "secureserver.net")
RUN_TEST(photos1_blogger_com, "photos1.blogger.com")
RUN_TEST(icann_org, "icann.org")
RUN_TEST(abc_net_au, "abc.net.au")
RUN_TEST(yadi_sk, "yadi.sk")
RUN_TEST(techcrunch_com, "techcrunch.com")
RUN_TEST(nhk_or_jp, "nhk.or.jp")
RUN_TEST(nginx_org, "nginx.org")
RUN_TEST(buzzfeed_com, "buzzfeed.com")
RUN_TEST(britannica_com, "britannica.com")
RUN_TEST(bp3_blogger_com, "bp3.blogger.com")
RUN_TEST(hollywoodreporter_com, "hollywoodreporter.com")
RUN_TEST(scoop_it, "scoop.it")
RUN_TEST(biglobe_ne_jp, "biglobe.ne.jp")
RUN_TEST(trustpilot_com, "trustpilot.com")
RUN_TEST(huffpost_com, "huffpost.com")
RUN_TEST(forms_gle, "forms.gle")
RUN_TEST(a8_net, "a8.net")
RUN_TEST(lemonde_fr, "lemonde.fr")
RUN_TEST(npr_org, "npr.org")
RUN_TEST(guardian_co_uk, "guardian.co.uk")
RUN_TEST(spotify_com, "spotify.com")
RUN_TEST(amazon_it, "amazon.it")
RUN_TEST(ria_ru, "ria.ru")
RUN_TEST(ted_com, "ted.com")
RUN_TEST(imageshack_us, "imageshack.us")
RUN_TEST(kickstarter_com, "kickstarter.com")
RUN_TEST(list_manage_com, "list-manage.com")
RUN_TEST(columbia_edu, "columbia.edu")
RUN_TEST(gnu_org, "gnu.org")
RUN_TEST(google_nl, "google.nl")
RUN_TEST(playstation_com, "playstation.com")
RUN_TEST(repubblica_it, "repubblica.it")
RUN_TEST(cbsnews_com, "cbsnews.com")
RUN_TEST(my_yahoo_com, "my.yahoo.com")
RUN_TEST(ibm_com, "ibm.com")
RUN_TEST(dan_com, "dan.com")
RUN_TEST(urbandictionary_com, "urbandictionary.com")
RUN_TEST(sciencedaily_com, "sciencedaily.com")
RUN_TEST(google_com_tw, "google.com.tw")
RUN_TEST(bloglovin_com, "bloglovin.com")
RUN_TEST(yelp_com, "yelp.com")
RUN_TEST(elmundo_es, "elmundo.es")
RUN_TEST(amazon_fr, "amazon.fr")
RUN_TEST(umich_edu, "umich.edu")
RUN_TEST(news_com_au, "news.com.au")
RUN_TEST(bp1_blogger_com, "bp1.blogger.com")
RUN_TEST(naver_jp, "naver.jp")
RUN_TEST(disqus_com, "disqus.com")
RUN_TEST(theatlantic_com, "theatlantic.com")
RUN_TEST(finance_yahoo_com, "finance.yahoo.com")
RUN_TEST(loc_gov, "loc.gov")
RUN_TEST(php_net, "php.net")
RUN_TEST(cbc_ca, "cbc.ca")
RUN_TEST(www_over_blog_com, "www.over-blog.com")
RUN_TEST(ggpht_com, "ggpht.com")
RUN_TEST(pixabay_com, "pixabay.com")
RUN_TEST(yandex_ru, "yandex.ru")
RUN_TEST(cisco_com, "cisco.com")
RUN_TEST(parallels_com, "parallels.com")
RUN_TEST(dw_com, "dw.com")
RUN_TEST(pexels_com, "pexels.com")
RUN_TEST(addtoany_com, "addtoany.com")
RUN_TEST(lg_com, "lg.com")
RUN_TEST(storage_googleapis_com, "storage.googleapis.com")
RUN_TEST(quora_com, "quora.com")
RUN_TEST(netflix_com, "netflix.com")
RUN_TEST(tes_com, "tes.com")
RUN_TEST(gizmodo_com, "gizmodo.com")
RUN_TEST(orkut_com_br, "orkut.com.br")
RUN_TEST(weibo_com, "weibo.com")
RUN_TEST(000webhost_com, "000webhost.com")
RUN_TEST(nypost_com, "nypost.com")
RUN_TEST(ja_wikipedia_org, "ja.wikipedia.org")
RUN_TEST(express_co_uk, "express.co.uk")
RUN_TEST(marriott_com, "marriott.com")
RUN_TEST(newsweek_com, "newsweek.com")
RUN_TEST(mozilla_com, "mozilla.com")
RUN_TEST(noaa_gov, "noaa.gov")
RUN_TEST(imageshack_com, "imageshack.com")
RUN_TEST(bp2_blogger_com, "bp2.blogger.com")
RUN_TEST(google_co_in, "google.co.in")
RUN_TEST(worldbank_org, "worldbank.org")
RUN_TEST(windowsphone_com, "windowsphone.com")
RUN_TEST(ovh_net, "ovh.net")
RUN_TEST(bt_com, "bt.com")
RUN_TEST(sapo_pt, "sapo.pt")
RUN_TEST(goodreads_com, "goodreads.com")
RUN_TEST(vice_com, "vice.com")
RUN_TEST(xinhuanet_com, "xinhuanet.com")
RUN_TEST(over_blog_kiwi_com, "over-blog-kiwi.com")
RUN_TEST(researchgate_net, "researchgate.net")
RUN_TEST(economist_com, "economist.com")
RUN_TEST(ovh_co_uk, "ovh.co.uk")
RUN_TEST(digg_com, "digg.com")
RUN_TEST(instagram_com, "instagram.com")
RUN_TEST(photobucket_com, "photobucket.com")
RUN_TEST(usnews_com, "usnews.com")
RUN_TEST(mega_nz, "mega.nz")
RUN_TEST(alibaba_com, "alibaba.com")
RUN_TEST(mashable_com, "mashable.com")
RUN_TEST(deezer_com, "deezer.com")
RUN_TEST(asus_com, "asus.com")
RUN_TEST(nginx_com, "nginx.com")
RUN_TEST(iubenda_com, "iubenda.com")
RUN_TEST(netvibes_com, "netvibes.com")
RUN_TEST(pl_wikipedia_org, "pl.wikipedia.org")
RUN_TEST(qq_com, "qq.com")
RUN_TEST(yale_edu, "yale.edu")
RUN_TEST(bitly_com, "bitly.com")
RUN_TEST(espn_com, "espn.com")
RUN_TEST(pbs_org, "pbs.org")
RUN_TEST(doubleclick_net, "doubleclick.net")
RUN_TEST(sciencemag_org, "sciencemag.org")
RUN_TEST(rapidshare_com, "rapidshare.com")
RUN_TEST(nydailynews_com, "nydailynews.com")
RUN_TEST(indiatimes_com, "indiatimes.com")
RUN_TEST(google_pl, "google.pl")
RUN_TEST(ikea_com, "ikea.com")
RUN_TEST(blackberry_com, "blackberry.com")
RUN_TEST(naver_com, "naver.com")
RUN_TEST(google_co_id, "google.co.id")
RUN_TEST(4shared_com, "4shared.com")
RUN_TEST(nbcnews_com, "nbcnews.com")
RUN_TEST(shopify_com, "shopify.com")
RUN_TEST(welt_de, "welt.de")
RUN_TEST(asahi_com, "asahi.com")
RUN_TEST(ea_com, "ea.com")
RUN_TEST(princeton_edu, "princeton.edu")
RUN_TEST(latimes_com, "latimes.com")
RUN_TEST(mit_edu, "mit.edu")
RUN_TEST(t_co, "t.co")
RUN_TEST(nvidia_com, "nvidia.com")
RUN_TEST(cambridge_org, "cambridge.org")
RUN_TEST(disney_com, "disney.com")
RUN_TEST(sciencedirect_com, "sciencedirect.com")
RUN_TEST(eventbrite_com, "eventbrite.com")
RUN_TEST(vox_com, "vox.com")
RUN_TEST(engadget_com, "engadget.com")
RUN_TEST(unesco_org, "unesco.org")
RUN_TEST(wikihow_com, "wikihow.com")
RUN_TEST(goo_ne_jp, "goo.ne.jp")
RUN_TEST(ox_ac_uk, "ox.ac.uk")
RUN_TEST(gmail_com, "gmail.com")
RUN_TEST(thetimes_co_uk, "thetimes.co.uk")
RUN_TEST(nikkei_com, "nikkei.com")
RUN_TEST(stanford_edu, "stanford.edu")
RUN_TEST(metro_co_uk, "metro.co.uk")
RUN_TEST(tripadvisor_com, "tripadvisor.com")
RUN_TEST(smh_com_au, "smh.com.au")
RUN_TEST(mystrikingly_com, "mystrikingly.com")
RUN_TEST(mysql_com, "mysql.com")
RUN_TEST(rambler_ru, "rambler.ru")
RUN_TEST(twitch_tv, "twitch.tv")
RUN_TEST(it_wikipedia_org, "it.wikipedia.org")
RUN_TEST(cornell_edu, "cornell.edu")
RUN_TEST(channel4_com, "channel4.com")
RUN_TEST(gofundme_com, "gofundme.com")
RUN_TEST(e_recht24_de, "e-recht24.de")
RUN_TEST(instructables_com, "instructables.com")
RUN_TEST(berkeley_edu, "berkeley.edu")
RUN_TEST(ru_wikipedia_org, "ru.wikipedia.org")
RUN_TEST(www_weebly_com, "www.weebly.com")
RUN_TEST(nokia_com, "nokia.com")
RUN_TEST(standard_co_uk, "standard.co.uk")
RUN_TEST(groups_google_com, "groups.google.com")
RUN_TEST(www_wikipedia_org, "www.wikipedia.org")
RUN_TEST(akamaihd_net, "akamaihd.net")
RUN_TEST(whitehouse_gov, "whitehouse.gov")
RUN_TEST(sfgate_com, "sfgate.com")
RUN_TEST(academia_edu, "academia.edu")
RUN_TEST(shutterstock_com, "shutterstock.com")
RUN_TEST(psychologytoday_com, "psychologytoday.com")
RUN_TEST(target_com, "target.com")
RUN_TEST(id_wikipedia_org, "id.wikipedia.org")
RUN_TEST(ytimg_com, "ytimg.com")
RUN_TEST(box_com, "box.com")
RUN_TEST(adssettings_google_com, "adssettings.google.com")
RUN_TEST(rtve_es, "rtve.es")
RUN_TEST(washington_edu, "washington.edu")
RUN_TEST(apache_org, "apache.org")
RUN_TEST(wa_me, "wa.me")
RUN_TEST(nature_com, "nature.com")
RUN_TEST(cnbc_com, "cnbc.com")
RUN_TEST(godaddy_com, "godaddy.com")
RUN_TEST(bp0_blogger_com, "bp0.blogger.com")
RUN_TEST(wiley_com, "wiley.com")
RUN_TEST(sendspace_com, "sendspace.com")
RUN_TEST(nationalgeographic_com, "nationalgeographic.com")
RUN_TEST(fifa_com, "fifa.com")
RUN_TEST(abc_es, "abc.es")
RUN_TEST(google_ca, "google.ca")
RUN_TEST(zendesk_com, "zendesk.com")
RUN_TEST(spiegel_de, "spiegel.de")
RUN_TEST(utexas_edu, "utexas.edu")
RUN_TEST(theverge_com, "theverge.com")
RUN_TEST(about_com, "about.com")
RUN_TEST(surveymonkey_com, "surveymonkey.com")
RUN_TEST(variety_com, "variety.com")
RUN_TEST(ovh_com, "ovh.com")
RUN_TEST(googleblog_com, "googleblog.com")
RUN_TEST(fastcompany_com, "fastcompany.com")
RUN_TEST(yahoo_co_jp, "yahoo.co.jp")
RUN_TEST(www_livejournal_com, "www.livejournal.com")
RUN_TEST(ap_org, "ap.org")
RUN_TEST(nicovideo_jp, "nicovideo.jp")
RUN_TEST(marketwatch_com, "marketwatch.com")
RUN_TEST(excite_co_jp, "excite.co.jp")
RUN_TEST(stuff_co_nz, "stuff.co.nz")
RUN_TEST(weforum_org, "weforum.org")
RUN_TEST(so_net_ne_jp, "so-net.ne.jp")
RUN_TEST(history_com, "history.com")
RUN_TEST(amazon_in, "amazon.in")
RUN_TEST(gooyaabitemplates_com, "gooyaabitemplates.com")
RUN_TEST(evernote_com, "evernote.com")
RUN_TEST(intel_com, "intel.com")
RUN_TEST(airbnb_com, "airbnb.com")
RUN_TEST(house_gov, "house.gov")
RUN_TEST(cbslocal_com, "cbslocal.com")
RUN_TEST(mhlw_go_jp, "mhlw.go.jp")
RUN_TEST(rottentomatoes_com, "rottentomatoes.com")
RUN_TEST(cam_ac_uk, "cam.ac.uk")
RUN_TEST(mail_yahoo_com, "mail.yahoo.com")
RUN_TEST(prnewswire_com, "prnewswire.com")
RUN_TEST(jstor_org, "jstor.org")
RUN_TEST(sputniknews_com, "sputniknews.com")
RUN_TEST(soratemplates_com, "soratemplates.com")
RUN_TEST(archives_gov, "archives.gov")
RUN_TEST(disney_go_com, "disney.go.com")
RUN_TEST(behance_net, "behance.net")
RUN_TEST(newscientist_com, "newscientist.com")
RUN_TEST(teamviewer_com, "teamviewer.com")
RUN_TEST(thestar_com, "thestar.com")
RUN_TEST(debian_org, "debian.org")
RUN_TEST(sina_com_cn, "sina.com.cn")
RUN_TEST(allrecipes_com, "allrecipes.com")
RUN_TEST(eonline_com, "eonline.com")
RUN_TEST(ndtv_com, "ndtv.com")
RUN_TEST(greenpeace_org, "greenpeace.org")
RUN_TEST(indiegogo_com, "indiegogo.com")
RUN_TEST(fda_gov, "fda.gov")
RUN_TEST(cmu_edu, "cmu.edu")
RUN_TEST(pcmag_com, "pcmag.com")
RUN_TEST(ehow_com, "ehow.com")
RUN_TEST(discovery_com, "discovery.com")
RUN_TEST(ask_fm, "ask.fm")
RUN_TEST(biblegateway_com, "biblegateway.com")
RUN_TEST(narod_ru, "narod.ru")
RUN_TEST(foursquare_com, "foursquare.com")
RUN_TEST(slate_com, "slate.com")
RUN_TEST(csmonitor_com, "csmonitor.com")
RUN_TEST(daum_net, "daum.net")
RUN_TEST(axs_com, "axs.com")
RUN_TEST(fortune_com, "fortune.com")
RUN_TEST(bund_de, "bund.de")
RUN_TEST(feedproxy_google_com, "feedproxy.google.com")
RUN_TEST(gutenberg_org, "gutenberg.org")
RUN_TEST(espn_go_com, "espn.go.com")
RUN_TEST(ubuntu_com, "ubuntu.com")
RUN_TEST(merriam_webster_com, "merriam-webster.com")
RUN_TEST(unicef_org, "unicef.org")
RUN_TEST(softpedia_com, "softpedia.com")
RUN_TEST(techradar_com, "techradar.com")
RUN_TEST(dribbble_com, "dribbble.com")
RUN_TEST(e_monsite_com, "e-monsite.com")
RUN_TEST(wiktionary_org, "wiktionary.org")
RUN_TEST(usc_edu, "usc.edu")
RUN_TEST(alexa_com, "alexa.com")
RUN_TEST(usgs_gov, "usgs.gov")
RUN_TEST(outlook_com, "outlook.com")
RUN_TEST(20minutos_es, "20minutos.es")
RUN_TEST(psu_edu, "psu.edu")
RUN_TEST(scientificamerican_com, "scientificamerican.com")
RUN_TEST(amazon_ca, "amazon.ca")
RUN_TEST(newyorker_com, "newyorker.com")
RUN_TEST(viagens_com_br, "viagens.com.br")
RUN_TEST(politico_com, "politico.com")
RUN_TEST(com_com, "com.com")
RUN_TEST(www_skyrock_com, "www.skyrock.com")
RUN_TEST(thedailybeast_com, "thedailybeast.com")
RUN_TEST(xing_com, "xing.com")
RUN_TEST(ieee_org, "ieee.org")
RUN_TEST(statista_com, "statista.com")
RUN_TEST(consumerreports_org, "consumerreports.org")
RUN_TEST(lonelyplanet_com, "lonelyplanet.com")
RUN_TEST(weather_com, "weather.com")
RUN_TEST(blog_fc2_com, "blog.fc2.com")
RUN_TEST(gesetze_im_internet_de, "gesetze-im-internet.de")
RUN_TEST(zdnet_com, "zdnet.com")
RUN_TEST(chicagotribune_com, "chicagotribune.com")
RUN_TEST(etsy_com, "etsy.com")
RUN_TEST(interia_pl, "interia.pl")
RUN_TEST(tabelog_com, "tabelog.com")
RUN_TEST(discord_gg, "discord.gg")
RUN_TEST(answers_com, "answers.com")
RUN_TEST(search_yahoo_com, "search.yahoo.com")
RUN_TEST(amzn_to, "amzn.to")
RUN_TEST(dictionary_com, "dictionary.com")
RUN_TEST(answers_yahoo_com, "answers.yahoo.com")
RUN_TEST(ftc_gov, "ftc.gov")
RUN_TEST(sakura_ne_jp, "sakura.ne.jp")
RUN_TEST(www_nhs_uk, "www.nhs.uk")
RUN_TEST(sky_com, "sky.com")
RUN_TEST(thenextweb_com, "thenextweb.com")
RUN_TEST(livescience_com, "livescience.com")
RUN_TEST(autodesk_com, "autodesk.com")
RUN_TEST(example_com, "example.com")
RUN_TEST(uber_com, "uber.com")
RUN_TEST(businesswire_com, "businesswire.com")
RUN_TEST(salon_com, "salon.com")
RUN_TEST(cia_gov, "cia.gov")
RUN_TEST(redhat_com, "redhat.com")
RUN_TEST(chinadaily_com_cn, "chinadaily.com.cn")
RUN_TEST(kinja_com, "kinja.com")
RUN_TEST(megaupload_com, "megaupload.com")
RUN_TEST(khanacademy_org, "khanacademy.org")
RUN_TEST(ameblo_jp, "ameblo.jp")
RUN_TEST(plos_org, "plos.org")
RUN_TEST(ebay_co_uk, "ebay.co.uk")
































